services:
  postgres:
    image: postgres:16
    container_name: gateflow-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: gateflow-kafka
    ports:
      - "9092:9092"
    environment:
      # KRaft mode Essentials
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      CLUSTER_ID: 'CUH_Q402T7-DePFKCBO_kA'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093' # Points to itself
      
      # Listeners: This setup allows both Localhost (IDE) and Docker apps to connect
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      
      # Persistence & Dev Speed
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    volumes:
      - kafka-data:/var/lib/kafka/data

  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli
    stdin_open: true
    environment:
      - STRIPE_API_KEY=${STRIPE_API_KEY}
    tty: true
    command: ["listen", "--forward-to", "http://host.docker.internal:8081/api/v1/webhook/stripe"]


volumes:
  postgres_data:
  kafka-data:



