spring.application.name=tracknote

server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/gateflow}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET}

stripe.api.key=${STRIPE_API_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
outbox.relay.fixed-delay-ms=5000

STRIPE_FREE_PRICE_ID=${STRIPE_FREE_PRICE_ID:price_test_free}
STRIPE_PRO_PRICE_ID=${STRIPE_PRO_PRICE_ID:price_test_pro}

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never

logging.level.root=INFO
logging.level.com.tracknote=INFO
