spring.application.name=tracknote

//Server port
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/gateflow
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# Hibernate (JPA) settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.boot.autoconfigure.web=DEBUG
logging.level.org.hibernate=DEBUG
logging.level.root=INFO

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never

jwt.secret=${JWT_SECRET}

debug=true
logging.level.web=DEBUG

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.open-in-view=false

stripe.api.key=${STRIPE_API_KEY}
STRIPE_FREE_PRICE_ID=price_1T1EnPR6IbdhoH44JoiRfxFe
STRIPE_PRO_PRICE_ID=price_1T1EnpR6IbdhoH44W4A7dlBN

logging.file.path=logs

stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

spring.kafka.bootstrap-servers=localhost:9092
outbox.relay.fixed-delay-ms=5000

logging.level.org.hibernate.stat=WARN
logging.level.org.hibernate.orm=WARN
logging.level.io.StatisticalLoggingSessionEventListener=WARN
logging.level.org.apache.kafka.clients=WARN
logging.level.com.tracknote=INFO








